name: team_manager
description: A team manager

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0

  flutter:
    sdk: flutter

  provider: ^6.0.2
  json_annotation: ^4.0.1
  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  get_it: ^7.2.0
  environment_config: ^3.0.0
  datetime_picker_formfield: ^2.0.0
  fluttertoast: ^8.0.9
  firebase_storage: ^10.2.11
  path: ^1.8.0
  firebase_core: ^1.14.0
  file_picker: ^5.1.0
  firebase_auth: ^3.3.13
  loading_animations: ^2.2.0
  rxdart: ^0.27.3
  tuple: ^2.0.0
  flutter_dropzone: ^3.0.5
  mime_type: ^1.0.0
  multi_select_flutter: ^4.1.2
  flutter_rating_bar: ^4.0.0
  syncfusion_flutter_calendar: ^20.2.49

  openapi_generator_annotations: ^4.0.0
  flutter_colorpicker: ^1.0.3
  mask_text_input_formatter: ^2.4.0
  image: ^3.2.0
  jwt_decoder: ^2.0.1
dev_dependencies:
  analyzer: ^5.0.0
  build_runner: ^2.0.5
  json_serializable: ^6.3.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  openapi_generator: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - i18n/
