name: team_manager
description: A team manager

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter_localizations:
    sdk: flutter
  localization: ^2.1.0

  flutter:
    sdk: flutter

  provider: ^6.0.2
  json_annotation: ^4.0.1
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  get_it: ^7.2.0
  environment_config: ^3.0.0
  go_router: ^3.0.4
  datetime_picker_formfield: ^2.0.0
  multiselect_formfield: ^0.1.7
  fluttertoast: ^8.0.9
dev_dependencies:
  analyzer: ^1.7.2
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - i18n/
