// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:team_manager/environment_config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4nQa7bqv1l16_h1LfZ_FTSBUR9PMgG_8',
    appId: '1:667494274685:web:6807bbe05b9d9097fa0314',
    messagingSenderId: '667494274685',
    projectId: 'resourcemanager-2a15b',
    authDomain: 'resourcemanager-2a15b.firebaseapp.com',
    storageBucket: 'resourcemanager-2a15b.appspot.com',
    measurementId: 'G-B4981098CY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkyZM6TC1APhhSphU4sK-6X6CIzLJeb48',
    appId: '1:667494274685:android:eec29627ce9d164ffa0314',
    messagingSenderId: '667494274685',
    projectId: 'resourcemanager-2a15b',
    storageBucket: 'resourcemanager-2a15b.appspot.com',
  );
}
